### ISSUE TITLE
希望增加按钮可点击方法

### ISSUE THREAD

**Issue by AltriaTT** [lihangleo2/SmartLoadingView#1]
有这样一个业务场景：登陆操作的时候，默认按钮不可点击（cannotClick），当用户名和密码的EditText都输入内容的时按钮变为可点击状态。大概看了一下源码，好像没有可以恢复按钮状态为可点击状态的方法。

**Comment by lihangleo2** [comment]
有啊  恢复最初的状态有 reset啊

**Comment by lihangleo2** [comment]
主动设置不可点击是cannotClick()   重置状态是reset();我这个就是根据登录去做的自定义view，你说的功能都有，只是我介绍的时候没有说清楚。
