### ISSUE TITLE
不能设置默认状态

### ISSUE THREAD

**Issue by Silnt** [lihangleo2/SmartLoadingView#5]
不能设置默认就是对勾状态吗?
不如 一个关注列表 第一次进入关注了A 第二次进入的列表的时候 A的状态应该是已关注的吧 对勾状态
还有个问题 代码中调用 setText() 方法 不生效啊

**Comment by lihangleo2** [comment]
好的  你说的问题都存在，我抽时间改 改好了在这通知你

**Comment by justinelock** [comment]
> 不能设置默认就是对勾状态吗?
> 不如 一个关注列表 第一次进入关注了A 第二次进入的列表的时候 A的状态应该是已关注的吧 对勾状态
> 还有个问题 代码中调用 setText() 方法 不生效啊

我加了一个方法，
1.可以自定义文字，比如按钮 下一步，变成 完成，

@Override
    public void afterTextChanged(Editable s) {
        if (!TextUtils.isEmpty(binding.editPhone.getText().toString().trim()) && !TextUtils.isEmpty(binding.editPassWord.getText().toString().trim())) {
            binding.smartLoadingViewLogin.setSmartClickable(true);
            // 比如这里可以改变文字内容
            binding.smartLoadingViewLogin.resetText("按钮文字不起作用？");
        } else {
            binding.smartLoadingViewLogin.setSmartClickable(false);
        }
    }


在 600行这里，start() 方法下边
2.按钮 按下和 默认颜色

activity里
@Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        //点击edittxt外，关闭软键盘
        if (ev.getAction() == MotionEvent.ACTION_DOWN) {
            View v = getCurrentFocus();
            if (KeyBoardUtils.isShouldHideInput(v, ev)) {
                KeyBoardUtils.closeKeybord(binding.editPhone, LoginActivity.this);
                binding.editPhone.clearFocus();
            }
           // 按下颜色
            binding.btnLoadingLogin.backgroundChange(R.color.background_main); 
        } 
      // 松开时的颜色
       else if (ev.getAction() == MotionEvent.ACTION_UP) {
            binding.btnLoadingLogin.backgroundChange(R.color.status_background);
        } 
        return super.dispatchTouchEvent(ev);
    }

**Comment by lihangleo2** [comment]
现已修改为2.0.2感谢你的支持
